# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nucleosite_splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setStyleSheet("QFrame{\n"
"background-color: rgb(52, 31, 95);\n"
"color:rgb(220, 220, 220);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"background-color:rgb(165, 246, 255);\n"
"color: rgb(200,200,200);\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.frame.setFont(font)
        self.frame.setTabletTracking(False)
        self.frame.setAcceptDrops(False)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(0, 60, 661, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.title.setFont(font)
        self.title.setStyleSheet("color:rgb(47, 255, 130)")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.title_description = QtWidgets.QLabel(self.frame)
        self.title_description.setGeometry(QtCore.QRect(0, 140, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.title_description.setFont(font)
        self.title_description.setStyleSheet("color:rgb(165, 246, 255)")
        self.title_description.setAlignment(QtCore.Qt.AlignCenter)
        self.title_description.setObjectName("title_description")
        self.loading_label = QtWidgets.QLabel(self.frame)
        self.loading_label.setGeometry(QtCore.QRect(0, 290, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.loading_label.setFont(font)
        self.loading_label.setStyleSheet("color:rgb(165, 246, 255)")
        self.loading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.loading_label.setObjectName("loading_label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(40, 270, 581, 23))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color:rgb(98, 114, 164);\n"
"    color: rgb(180,180,180);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"border-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.494, x2:0.995025, y2:0.5, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255))\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.beta_label = QtWidgets.QLabel(self.frame)
        self.beta_label.setGeometry(QtCore.QRect(40, 350, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.beta_label.setFont(font)
        self.beta_label.setStyleSheet("color:rgb(98, 114, 164)")
        self.beta_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.beta_label.setObjectName("beta_label")
        self.verticalLayout.addWidget(self.frame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.title.setText(_translate("SplashScreen", "Nucleo<strong>Site"))
        self.title_description.setText(_translate("SplashScreen", "A Nuclear Siting Tool"))
        self.loading_label.setText(_translate("SplashScreen", "Loading..."))
        self.progressBar.setFormat(_translate("SplashScreen", "%p%"))
        self.beta_label.setText(_translate("SplashScreen", "Beta Version"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
